version: '3'
services:
    shopify_daily: 
        image: xiaoxiaorey/shopify_daily_spark3.0_hadoop3.2:v2.1
        environment: 
            - DATE_CONFIG=2019-04-07
            - AWS_ACCESS_KEY_ID=
            - AWS_SECRET_KEY=
            - AWS_BUCKET_NAME=
            - PG_DB_TYPE=
            - PG_DB_IP=
            - PG_DB_PORT=
            - PG_DB_NAME=
            - PG_DB_TBL=
            - PG_DB_USER=
            - PG_DB_PWD=